baseURL = 'https://ryynexx.github.io/'
languageCode = 'en-us'
title = 'ryynexx'

theme = 'hugo-PaperMod'

[params.profileMode]
    enabled = true
    title = "Rabeesha Ijaz"
    subtitle = "Breaking Down Bytes & Bits"
    imageUrl = "pfp1.jpg"
    imageTitle = "Profile Picture"
    imageWidth = 200
    imageHeight = 200

[[params.profileMode.buttons]]
    name = "About Me"
    url = "/about"

[[params.profileMode.buttons]]
    name = "Archives"
    url = "/archives"

[[menu.main]]
    name = "Tags"
    identifier = "tags"
    weight = 300
    url = "/tags/"

[[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts/"

[[menu.main]]
  name = "Search"
  url = "/search"

[params]
    dateform        = "Jan 2, 2006"
    dateformShort   = "Jan 2"
    dateformNum     = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04"
    ShowToc =  true
    ShowReadingTime = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true
    taglist = true
    defaultTheme = 'dark'
    lazyLoadImages = true  # Improves page load speed

[[params.socialIcons]]
    name = "github"
    url = "https://github.com/ryynexx"

[[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/rabeesha-ijaz-45424434b/"

[outputs]
  home = [ "HTML", "RSS", "JSON" ]

